### ISSUE TITLE
Was this effort abandoned?

### ISSUE THREAD

**Issue by CaptJakk** [erikd/hspec-hedgehog#1]
We just encountered a need for the same thing and I'm wondering if this effort had stalled out for fundamental reasons or whether you just had other priorities take over. I'm interested in trying to get this to work and would be willing to help. Unless of course it fundamentally won't work for some reason.

**Comment by erikd** [comment]
Yes it was basically abandoned, mainly because once I started working with Hedgehog I found I didn't really like Hspec much any more. More than happy for you or someone else to take this over.

**Comment by luc-tielen** [comment]
Are there any pointers on how to pick this up again/where to start? 
I would like to try and give a shot at it since I would like this myself 😄.

**Comment by erikd** [comment]
Yeah, I abandonded this. Decided I liked the way Hedgehog did tests better. Please feel free to fork this or start from scratch.

**Comment by parsonsmatt** [comment]
@erikd I'm working on a good integration; would you be willing to transfer the Hackage maintainership to me?

**Comment by erikd** [comment]
Of course!

**Comment by parsonsmatt** [comment]
I'm done with the initial release of my library: https://github.com/parsonsmatt/hspec-hedgehog

Once I get Hackage maintainership I'll post a version :)

**Comment by erikd** [comment]
Hackage maintainership has been transferred.
